apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: secret-test-gh-0327
  janus-idp.io/tekton: secret-test-gh-0327
  backstage.io/kubernetes-id: secret-test-gh-0327
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: secret-test-gh-0327
resources: 
- deployment.yaml
- route.yaml
- service.yaml
