apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: secret-test-gh-0327
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: secret-test-gh-0327 
  name: secret-test-gh-0327
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: secret-test-gh-0327 
